services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/

  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: server
    environment:
      - REDIS_URL=redis://redis-dev:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo-dev:27017/the_database

  mongo-dev:
    image: mongo
    ports:
      - 3456:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/01-mongo-init.js
      - mongo_data:/data/db # Named volume
    container_name: mongo

  redis-dev:
    image: redis
    ports:
      - 6379:6379
    command: ['sh', '-c', 'chown -R redis:redis /data && redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server
    container_name: reverse-proxy


volumes:
  mongo_data:

