services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/

  server:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: server
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/01-mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    command: ['sh', '-c', 'chown -R redis:redis /data && redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  nginx:
    image: nginx:1.25-alpine
    container_name: reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server


volumes:
  mongo_data:

